const STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  PENDING_HR_VALIDATION: 'PENDING_HR_VALIDATION',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  MANAGER_REJECTED: 'MANAGER_REJECTED',
  HR_REJECTED: 'HR_REJECTED',
  CANCELLED: 'CANCELLED',
});

const TERMINAL_STATUSES = Object.freeze([
  STATUS.COMPLETED,
  STATUS.MANAGER_REJECTED,
  STATUS.HR_REJECTED,
  STATUS.CANCELLED,
]);

const TASK_TYPES = Object.freeze({
  ORG_UPDATE: 'ORG_UPDATE',
  PAYROLL: 'PAYROLL',
  IT: 'IT',
  FACILITIES: 'FACILITIES',
});

const DOWNSTREAM_TASK_TYPES = Object.freeze([TASK_TYPES.PAYROLL, TASK_TYPES.IT, TASK_TYPES.FACILITIES]);

const TASK_STATUS = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
});

const ROLES = Object.freeze({
  EMPLOYEE: 'EMPLOYEE',
  MANAGER: 'MANAGER',
  HR: 'HR',
  PAYROLL: 'PAYROLL',
  IT: 'IT',
  FACILITIES: 'FACILITIES',
});

const EVENTS = Object.freeze({
  MANAGER_APPROVE: 'MANAGER_APPROVE',
  MANAGER_REJECT: 'MANAGER_REJECT',
  HR_APPROVE: 'HR_APPROVE',
  HR_REJECT: 'HR_REJECT',
  CANCEL: 'CANCEL',
  ALL_TASKS_DONE: 'ALL_TASKS_DONE',
});

module.exports = { STATUS, TERMINAL_STATUSES, TASK_TYPES, DOWNSTREAM_TASK_TYPES, TASK_STATUS, ROLES, EVENTS };
